# Generated by Django 5.1.2 on 2024-11-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Post',
            new_name='post',
        ),
    ]
